### ISSUE TITLE
Conditional assignment?

### ISSUE THREAD

**Issue by dhowe** [exodrifter/unity-rumor#53] opened 2017-12-23 06:21 UTC
````
$ foo = coinflip()      # returns 0 or 1

if foo == 0:
    $ child = "boy"

...
````

throws the following error:

````
Exodrifter.Rumor.Lang.CompilerError: at (25,16): Unexpected tokens after string!
  at Exodrifter.Rumor.Lang.RumorCompiler.CompileExpression (System.Collections.Generic.List`1 tokens) [0x006e3] in /Users/dhowe/git/tendAR/TendAR/Assets/Libraries/Rumor/Lang/RumorCompiler.cs:405 
  at Exodrifter.Rumor.Lang.RumorCompiler.CompileSay (Exodrifter.Rumor.Lang.LogicalLine line, System.Int32& pos, System.Collections.Generic.List`1 children) [0x00042] in /Users/dhowe/git/tendAR/TendAR/Assets/Libraries/Rumor/Lang/RumorCompiler.cs:593 
  at Exodrifter.Rumor.Lang.RumorCompiler.CompileNodes (System.Collections.Generic.List`1 lines, System.Int32& index, Int32 depth) [0x00106] in /Users/dhowe/git/tendAR/TendAR/Assets/Libraries/Rumor/Lang/RumorCompiler.cs:237 
  at Exodrifter.Rumor.Lang.RumorCompiler.Compile (System.String code) [0x001cf] in /Users/dhowe/git/tendAR/TendAR/Assets/Libraries/Rumor/Lang/RumorCompiler.cs:151 
  at Exodrifter.Rumor.Engine.Rumor..ctor (System.String script) [0x0000f] in /Users/dhowe/git/tendAR/TendAR/Assets/Libraries/Rumor/Engine/Rumor.cs:215 
  at ScriptedText.Start () [0x0000d] in /Users/dhowe/git/tendAR/TendAR/Assets/Tests/ScriptedTextTest/ScriptedText.cs:17 
UnityEngine.Debug:Log(Object)
ScriptedText:Start() (at Assets/Tests/ScriptedTextTest/ScriptedText.cs:21)

**Comment by exodrifter** [comment] 2017-12-23 06:38
Sorry, I haven't added support for adding comments on the same line as code yet (see #12).

You'll have to split the comment onto another line. As so:
```
# returns 0 or 1
$ foo = coinflip()
```

I agree this is pretty dumb, so I'm adding support for having comments on the same line as code in the compiler rehaul I hope to have done by early January.

**Comment by dhowe** [comment] 2017-12-23 07:30
I still get the same error without the comment, and it points to line of the indented assignment...

**Comment by exodrifter** [comment] 2017-12-23 16:10
I was not able to reproduce your error. On closer exception, the compiler is complaining about a line with a `say` command, so maybe you accidentally left a semicolon or some other non-whitespace character at the end of one of your say statements?

I did, however, find a bug with `if` conditional statements requiring a following `else` or `elif` statement to compile. I also made the error message you're encountering more descriptive. These changes are in [1.1.2](https://github.com/exodrifter/unity-rumor/releases/tag/1.1.2).

Let me know if these changes help.

**Comment by dhowe** [comment] 2017-12-24 08:17
Hmm, let me come up with a better test... how do you 'say' a variable?
This doesn't seem to work:

label start:
    say "hello"
    $ foo = "goodbye"
    say foo

**Comment by exodrifter** [comment] 2017-12-26 02:00
I'm currently on holiday, so thank you for your patience.

I had some time to look at it today and it's a bug with how the compiler treats Expressions in say statements. When you do:
```
say foo
```
The compiler thinks you want a say statement with a character with the value of `foo` saying nothing. What the compiler _should_ do is notice that it's much preferable to have the default character say the value of `foo` instead.

Unfortunately, fixing this problem might be too difficult to warrant a fix since I'm already working on a compiler rehaul right now. I will take a look at this while I'm on the road tomorrow, but for now, try these workarounds:
```
$ me = "me"
$ foo = "goodbye"

say "" + foo
say me foo
say me "" + foo
say me foo + ""
```

For added clarity, these examples **won't** work. The last three examples are probably the ones that caused the error you got when you first made this ticket:
```
$ me = "me"
$ foo = "goodbye"

say foo + ""
say "me" foo
say "me" "" + foo
say "me" foo + ""
```

**Comment by exodrifter** [comment] 2017-12-26 07:42
I managed to have some time to look at it tonight, and unfortunately this won't be something I will be able to fix for the current major version since the fix required is essentially the compiler rehaul I'm working on.

This is a known problem in the current version (see [6408112/Lang/RumorCompiler.cs:593](https://github.com/exodrifter/unity-rumor/blob/6408112e5db48761535f8ec08569af108cca5dad/Lang/RumorCompiler.cs#L593))

I'll update this ticket when the compiler rehaul is done.

**Comment by exodrifter** [comment] 2018-01-02 07:36
If you'd like to check it out, this error is now fixed on the bleeding edge of the `refactor_compiler` branch (see [caaca4f](https://github.com/exodrifter/unity-rumor/commit/caaca4f92ff589f0bee9856895d440373f44f9d2)).

Please be warned that the `refactor_compiler` branch is **NOT FULLY FUNCTIONAL** and is prone to frequent rebasing and potential drastic API changes. I am still working on the overhaul, but you should be able to do this now:

```
$ foo = "foo"
$ bar = "bar"
say foo + bar "Hello, " + "World!"
say "foo" + bar "Hello, " + bar + "!"
```

Anyway, I just wanted to give an update on the progress. I have a lot more unit tests to write and a lot more API changes to make as well. Again, the `refactor_compiler` branch is **NOT STABLE** and you should not check it out unless you're just curious or something, idk.

**Comment by exodrifter** [comment] 2018-01-15 17:04
PR #58 merged.

**Closed by exodrifter** 2018-01-15 17:04 UTC
Labels: bug
